import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { crestPath, pathYRange, plateMix, seaPaint } from '../src/pages/ship/sea.ts'

describe('sea scale', () => {
  it('slides from glassy sun to a dark chop', () => {
    const perfect = seaPaint(1)
    const flat = seaPaint(0.6)
    const worst = seaPaint(0)
    assert.ok(perfect.amp < flat.amp)
    assert.ok(flat.amp < worst.amp)
    assert.ok(perfect.freq < worst.freq)
    assert.ok(perfect.sunY < flat.sunY)
    assert.ok(flat.sunY < worst.sunY)
    assert.equal(perfect.rain, 0)
    assert.equal(flat.rain, 0)
    assert.equal(worst.rain, 1)
    assert.ok(perfect.glitter > worst.glitter)
    assert.ok(perfect.displace < worst.displace)
    assert.ok(perfect.shade < worst.shade)
    const mid = seaPaint(0.5)
    assert.ok(mid.amp > perfect.amp && mid.amp < worst.amp)
    assert.ok(mid.sunY > perfect.sunY && mid.sunY < worst.sunY)
  })

  it('crossfades the clear, flat, and storm plates on the same line', () => {
    const clear = plateMix(1)
    const flat = plateMix(0.6)
    const storm = plateMix(0)
    assert.equal(clear.clear, 1)
    assert.equal(clear.flat, 0)
    assert.equal(clear.storm, 0)
    assert.equal(flat.flat, 1)
    assert.equal(flat.clear, 0)
    assert.equal(flat.storm, 0)
    assert.equal(storm.storm, 1)
    assert.equal(storm.flat, 0)
    const up = plateMix(0.8)
    assert.ok(Math.abs(up.clear - 0.5) < 1e-9)
    assert.ok(Math.abs(up.flat - 0.5) < 1e-9)
    assert.equal(up.storm, 0)
    const down = plateMix(0.3)
    assert.ok(Math.abs(down.flat - 0.5) < 1e-9)
    assert.ok(Math.abs(down.storm - 0.5) < 1e-9)
    assert.equal(down.clear, 0)
  })

  it('draws a taller crest when the sea is worse', () => {
    const calm = seaPaint(1)
    const storm = seaPaint(0)
    const calmRange = pathYRange(crestPath(520, calm.amp, calm.freq, 0.4))
    const stormRange = pathYRange(crestPath(520, storm.amp, storm.freq, 0.4))
    assert.ok(stormRange > calmRange * 3, `${stormRange} vs ${calmRange}`)
  })
})
